### ISSUE TITLE
Building on Linux: Base operand '->' has non-pointer type

### ISSUE THREAD

**Issue by chuck-knox** [fosbob/MasterPassword-Material#2]
Hi @fosbob , thank for making MasterPassword-Material. This application is so polished and well-done, I've been using it on all of my Windows machines for a while now.

I've been trying to build it on Linux for equally as long, and to no avail. I am creating this issue in an effort to try and uncover what the flaw in my build process is. I would like to add that C++ and Qt are not my strong suits, so feel free to ask any and every question you might have about the build process.

I've been using Docker to automate the build process. Hopefully you are familiar with it. If not, it's not a big deal -- the build steps are easy to follow from the Dockerfile (which I'll include).

Here's the problem I've run into in every attempt, which comes from running `make` in your `README.md` Linux build steps section:

```
../src/importer.cc: In static member function 'static QList<Site> Importer::parseJson(QFile&)':
../src/importer.cc:33:25: error: base operand of '->' has non-pointer type 'QJsonArray::iterator'
     QJsonObject site = i->toObject();
                         ^
Makefile:662: recipe for target 'importer.o' failed
make: *** [importer.o] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2
```

The file and code snippet in question, `importer.cc`, looks like this:

```c++
#include "importer.h"

QList<Site> Importer::parseJson(QFile &file)
{
  file.open(QIODevice::ReadOnly | QIODevice::Text);
  QList<Site> out;

  QJsonDocument doc = QJsonDocument::fromJson(file.readAll());

  QJsonArray sites = doc.array();
  for (QJsonArray::iterator i=sites.begin(); i != sites.end(); i++)
  {
    QJsonObject site = i->toObject();

    Content *password;
    Content *login;
    Content *answer;
    QString url;
....
```
I looked up the documentation for `QJsonDocument.array()` [here](http://doc.qt.io/qt-5/qjsonvalue.html) and the closest thing I was able to find was nearby at this [page](http://doc.qt.io/qt-5/qjsonvalue.html), `QJsonValue.toObject()`. 

Is it possible that the definition of these objects has changed since a year ago's commits? Could that be causing the problems?

I sadly don't have much more time available to me to deep-dive into the code and work on it tonight, but perhaps we could figure it out over time. 

I mentioned the Dockerfile earlier, which describes the build process. I have it [here](https://github.com/chuck-knox/my-dockerfiles/blob/master/mpw/Dockerfile) in one of my repos, but I'll paste it here too:

```Dockerfile
FROM debian
# First install qt dependencies
RUN apt-get clean && apt-get update && apt-get install -y git-svn git wget qt5-default qt5-qmake build-essential libqt5svg5* qtdeclarative5-dev qtbase5-dev libssl-dev automake autoconf
RUN mkdir /mpw
WORKDIR /mpw
# Install qml-material
RUN wget https://github.com/papyros/qml-material/archive/v0.2.0.tar.gz && \
	tar -xvf v0.2.0.tar.gz
WORKDIR /mpw/qml-material-0.2.0
RUN mkdir build
WORKDIR /mpw/qml-material-0.2.0/build
RUN qmake /mpw/qml-material-0.2.0/qml-material.pro
RUN make
RUN make install
# Install MasterPassword-Material
WORKDIR /mpw
#Pointing away from the official release for now.
#RUN wget https://github.com/fosbob/MasterPassword-Material/archive/v1.0.tar.gz && \
#	tar -xvf v1.0.tar.gz
RUN git clone https://github.com/chuck-knox/MasterPassword-Material.git
WORKDIR /mpw/MasterPassword-Material
# (this next step is so that the ./prepare shebang points to a valid binary)
RUN ln -s /bin/bash /usr/bin/bash
RUN ./prepare
RUN mkdir build
WORKDIR /mpw/MasterPassword-Material/build
RUN qmake ../masterpassword-material.pro -r -spec linux-g++
RUN make
```

You'll notice that I clone my own fork of your project. The 3 differences between your master branch and my fork are:
* I changed `#!/usr/bin/bash` to `#!/bin/bash` 
* I changed the `git svn` command to plain-old `git`
* The scrypt google code website points to a github repo, so in the `git` line I pointed the clone target to it

Thanks again for making some great software! Looking forward to building it and possibly offering some contributions in the future.

**Comment by fosbob** [comment]
Hi @chuck-knox,
Many thanks for your reply. Great you like it!

I've updated the project so the build is working again and it was running fine on my Arch system. 
It seems that Debian uses an older version of Qt where the pointer operator for QJsonArray::iterator is not supported, hence the error you encounter.

To fix this, I just replaced `i->toObject()` with `(*i).toObject()` and tested it with your Dockerfile.
It completed without errors, but please try for yourself and let me know if it's working :)

**Comment by chuck-knox** [comment]
Hey @fosbob, thanks for updating the project and making the fix! I was also able to get it to build after your changes. I'll close the issue now -- I havent had the opportunity to run it (been busy with work), but I'll try it out this weekend and if I still can't get it to run I'll leave a comment here. But the issue is definitely resolved so I'll close it up.

I'm curious, do you do your Qt development on your Arch box? I've tried installing QtCreator on my Windows machine and it did not work out very well. But if I can do development on my Arch box, that would be pretty cool -- if there's anything you can tell me about your dev environment, I'd love to hear it.

**Comment by fosbob** [comment]
Yes, I do everything on Arch Linux (I don't touch Windows if I don't have to) and I'm very happy with it.
QtCreator works fine, but mostly I use the terminal to run compilation tasks.
I think there is nothing special about my environment - just Arch and some applicatons.
But if you want more details, just let me know. I hope I can help you.

**Comment by chuck-knox** [comment]
If there's nothing special about your environment, and you say it's just on Arch, I can probably figure it out on my own then. Ultimately, I was just wondering if there was anything special or out-of-the-ordinary. Thanks!
